import {
  Area,
  CartesianGrid,
  ComposedChart,
  Line,
  ReferenceLine,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from 'recharts'
import { useMemo } from 'react'
import type { ForecastRow } from '../data/analyticsData'

type ChartRow = ForecastRow & {
  bandBase: number
  bandSpan: number
}

export function ForecastChart({ data }: { data: ForecastRow[] }) {
  const chartData = useMemo(() => {
    return data.map((d): ChartRow => {
      const has =
        d.forecast != null &&
        typeof d.upper === 'number' &&
        typeof d.lower === 'number'
      const lower = has ? (d.lower as number) : 0
      const upper = has ? (d.upper as number) : 0
      return {
        ...d,
        bandBase: lower,
        bandSpan: has ? Math.max(0, upper - lower) : 0,
      }
    })
  }, [data])

  return (
    <div className="rounded-2xl border border-gray-100 bg-white p-6 shadow-sm">
      <h3 className="font-semibold text-[#1F2937]">48-Hour Risk Forecast — Team Average</h3>
      <p className="mt-0.5 text-xs text-gray-400">
        Bi-LSTM temporal model prediction with confidence interval · shaded area = uncertainty band
      </p>

      <div className="mt-4 h-[240px] w-full">
        <ResponsiveContainer width="100%" height="100%">
          <ComposedChart data={chartData} margin={{ top: 12, right: 12, left: -8, bottom: 4 }}>
            <CartesianGrid strokeDasharray="3 3" stroke="#F9FAFB" />
            <XAxis dataKey="day" tick={{ fontSize: 11, fill: '#6B7280' }} interval={1} />
            <YAxis domain={[40, 100]} tick={{ fontSize: 11, fill: '#9CA3AF' }} />
            <Tooltip
              contentStyle={{
                borderRadius: 12,
                border: '1px solid #E5E7EB',
                boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.06)',
                fontSize: 12,
              }}
            />
            {/* Confidence band via stacked Areas: transparent lower block + tinted width */}
            <Area
              type="linear"
              dataKey="bandBase"
              stackId="ci"
              stroke="none"
              fill="transparent"
              isAnimationActive={false}
              name=""
            />
            <Area
              type="linear"
              dataKey="bandSpan"
              stackId="ci"
              stroke="none"
              fill="#1E3A8A"
              fillOpacity={0.14}
              isAnimationActive={false}
              name=""
            />
            <Line
              type="monotone"
              dataKey="actual"
              name="Actual (observed)"
              stroke="#1E3A8A"
              strokeWidth={2.5}
              dot={{ fill: '#1E3A8A', r: 4 }}
              connectNulls={false}
              isAnimationActive={false}
            />
            <Line
              type="monotone"
              dataKey="forecast"
              name="Forecast (Bi-LSTM)"
              stroke="#7C3AED"
              strokeWidth={2.5}
              strokeDasharray="6 3"
              dot={{ fill: '#7C3AED', r: 4 }}
              connectNulls={false}
              isAnimationActive={false}
            />
            <ReferenceLine
              x="Day 7"
              stroke="#9CA3AF"
              strokeDasharray="4 4"
              label={{ value: 'Now', position: 'top', fontSize: 10, fill: '#9CA3AF' }}
            />
          </ComposedChart>
        </ResponsiveContainer>
      </div>

      <div className="mt-4 flex flex-wrap items-center gap-4 border-t border-gray-50 pt-3 text-[11px] text-gray-500">
        <span className="inline-flex items-center gap-1.5">
          <span className="inline-block h-0.5 w-6 bg-[#1E3A8A]" />
          Actual (blue solid)
        </span>
        <span className="inline-flex items-center gap-1.5">
          <span
            className="inline-block h-0.5 w-6"
            style={{
              background: 'repeating-linear-gradient(90deg, #7C3AED 0, #7C3AED 6px, transparent 6px, transparent 9px)',
            }}
          />
          Forecast (purple dashed)
        </span>
        <span className="inline-flex items-center gap-1.5">
          <span className="inline-block h-3 w-6 rounded bg-[#1E3A8A]/15" />
          Confidence interval (blue shaded)
        </span>
      </div>

      <p className="mt-3 text-xs italic text-gray-400">
        Forecast generated by Bi-LSTM temporal model trained on TILES-2018 sequential workload features.
        Confidence interval represents ±1 standard deviation of model uncertainty. This addresses Research
        Objective 3: temporal pattern detection and risk accumulation modeling.
      </p>
    </div>
  )
}
