// PP1 backend → frontend integration layer.
//
// `manifest.json` is generated by Codes/demo/build_demo_predictions.py — it
// carries the real Fusion + Posture model output for 24 held-out test
// sequences, one per patient slot in the ward.
//
// The store loads this once on startup; afterwards every patient card on
// every tab displays values that originated from the trained models.

import type { RiskLevel, PostureType } from '../types'

export interface DemoEntry {
  patientId: string
  room: string
  bed: number
  source: 'UR' | 'NTU'
  sequenceId: string
  actionLabel: string | null
  skeletonFile: string
  riskLevel: RiskLevel
  riskScore: number
  posture: PostureType
  confidence: number          // fusion-model max softmax probability
  posturePrior: number        // posture-model max softmax probability
  pLow: number
  pModerate: number
  pHigh: number
  rfLow: number | null
  rfModerate: number | null
  rfHigh: number | null
  stgcnLow: number | null
  stgcnModerate: number | null
  stgcnHigh: number | null
  groundTruth: RiskLevel
  correct: boolean
  modality: string            // 'RGB→Skeleton' or 'Motion-Capture Skeleton'
  actionDescription: string   // plain-English description of the source action
  justification: string       // why the model classified this sequence the way it did
  features: {
    vertical_drop: number
    sudden_vertical_change: number
    torso_angle_max: number
    torso_angle_mean: number
    instability_score: number
    max_joint_speed: number
    mean_joint_speed: number
    center_speed_max: number
  } | null
}

export interface DemoManifest {
  evaluationProtocol: string
  testSetSize: number
  modelAccuracy: Record<string, number>
  totalPatients: number
  correctCount: number
  entries: DemoEntry[]
}

let cached: DemoManifest | null = null

export async function loadManifest(): Promise<DemoManifest | null> {
  if (cached) return cached
  try {
    const res = await fetch('/demo_data/manifest.json', { cache: 'no-store' })
    if (!res.ok) return null
    cached = (await res.json()) as DemoManifest
    return cached
  } catch {
    return null
  }
}

export function getEntry(manifest: DemoManifest | null, patientId: string): DemoEntry | undefined {
  return manifest?.entries.find(e => e.patientId === patientId)
}
