import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ArrowLeft, ArrowRightLeft, Download, Info } from 'lucide-react'
import type { RedistributionSuggestion, SuggestionStatus } from '../types/deterioration.types'
import {
  REDISTRIBUTION_SUGGESTIONS,
  WORKLOAD_ENTRIES,
} from '../data/redistributionData'
import { ImpactPreviewChart } from '../components/ImpactPreviewChart'
import { RedistributionCard } from '../components/RedistributionCard'
import { WorkloadBarChart } from '../components/WorkloadBarChart'

export function WorkloadRedistributionPage() {
  const navigate = useNavigate()
  const [suggestions, setSuggestions] =
    useState<RedistributionSuggestion[]>(REDISTRIBUTION_SUGGESTIONS)

  const [activeFilter, setActiveFilter] = useState<SuggestionStatus | 'all'>('all')

  const overloadedCount = useMemo(
    () => WORKLOAD_ENTRIES.filter((e) => e.currentLoad > 80).length,
    [],
  )

  const handleApprove = (id: string) => {
    setSuggestions((prev) => prev.map((s) => (s.id === id ? { ...s, status: 'approved' } : s)))
  }

  const handleReject = (id: string) => {
    setSuggestions((prev) => prev.map((s) => (s.id === id ? { ...s, status: 'rejected' } : s)))
  }

  const handleModify = (id: string) => {
    window.alert(
      `Modify suggestion ${id}:\n\n` +
        `In the full system, this opens an edit modal where supervisors can adjust which tasks are transferred and select a different receiving caregiver.\n\n` +
        `This feature is marked for Sprint 2 implementation.`,
    )
  }

  const handleUndoReject = (id: string) => {
    setSuggestions((prev) => prev.map((s) => (s.id === id ? { ...s, status: 'pending' } : s)))
  }

  const approvedIds = suggestions.filter((s) => s.status === 'approved').map((s) => s.id)

  const pendingCount = suggestions.filter((s) => s.status === 'pending').length

  const approvedCount = suggestions.filter((s) => s.status === 'approved').length

  const filteredSuggestions =
    activeFilter === 'all' ? suggestions : suggestions.filter((s) => s.status === activeFilter)

  const totalProjectedReduction = suggestions
    .filter((s) => s.status === 'approved')
    .reduce((sum, s) => sum + s.impactScore, 0)

  return (
    <div className="space-y-6">
      <button
        type="button"
        onClick={() => navigate('/deterioration')}
        className="flex items-center gap-2 text-sm text-[#2563EB] hover:underline"
      >
        <ArrowLeft size={16} aria-hidden />
        Back to Deterioration Detection
      </button>

      <div className="flex flex-wrap items-start justify-between gap-4">
        <div>
          <div className="flex flex-wrap items-center gap-3">
            <h1 className="text-2xl font-bold text-[#1F2937]">Adaptive Workload Redistribution</h1>
            <span className="inline-flex items-center gap-1.5 rounded-full border border-amber-200 bg-amber-50 px-3 py-1 text-xs font-medium text-amber-700">
              <span className="inline-block h-2 w-2 animate-pulse rounded-full bg-amber-500" />
              Hosseini Nurse Dataset
            </span>
          </div>
          <p className="mt-1 text-sm text-gray-500">
            AI-generated redistribution suggestions based on risk scores, baseline deviations, and
            capacity analysis · TILES-2018 Dataset
          </p>
        </div>

        <button
          type="button"
          className="flex items-center gap-2 rounded-xl border border-gray-200 px-4 py-2 text-sm text-gray-500 transition-colors hover:bg-gray-50"
          onClick={() =>
            window.alert('Export Report: wire-up to PDF/CSV export is planned for a future sprint.')
          }
        >
          <Download size={14} aria-hidden />
          Export Report
        </button>
      </div>

      <div className="flex gap-3 rounded-2xl border border-blue-100 bg-blue-50 p-4">
        <Info size={18} className="mt-0.5 shrink-0 text-[#2563EB]" aria-hidden />
        <div>
          <p className="text-sm font-medium text-[#1E3A8A]">
            Research Objective 6 — Adaptive Workload Redistribution
          </p>
          <p className="mt-0.5 text-xs text-blue-700">
            Suggestions generated by comparing caregiver risk scores, personal baseline deviations, and
            available capacity. This bridges the gap between deterioration detection and actionable
            intervention identified in Sendak et al. (2020) and Rajkomar et al. (2019). Approve, modify,
            or reject each suggestion below.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-2 gap-4 sm:grid-cols-4">
        <div className="rounded-2xl border border-gray-100 bg-white p-4 shadow-sm">
          <p className="text-xs font-medium text-gray-400">Pending Review</p>
          <p className="mt-1 text-3xl font-bold text-[#1F2937]">{pendingCount}</p>
          <p className="mt-0.5 text-xs text-gray-400">suggestions</p>
        </div>
        <div className="rounded-2xl border border-gray-100 bg-white p-4 shadow-sm">
          <p className="text-xs font-medium text-gray-400">Approved</p>
          <p className="mt-1 text-3xl font-bold text-green-600">{approvedCount}</p>
          <p className="mt-0.5 text-xs text-gray-400">redistributions</p>
        </div>
        <div className="rounded-2xl border border-gray-100 bg-white p-4 shadow-sm">
          <p className="text-xs font-medium text-gray-400">Projected Risk Reduction</p>
          <p className="mt-1 text-3xl font-bold text-[#1E3A8A]">
            {totalProjectedReduction > 0 ? `−${totalProjectedReduction}` : '0'}
          </p>
          <p className="mt-0.5 text-xs text-gray-400">total risk points</p>
        </div>
        <div
          className="rounded-2xl border border-orange-100 bg-white p-4 shadow-sm"
          style={{ borderLeftWidth: 4, borderLeftColor: '#EA580C' }}
        >
          <p className="text-xs font-medium text-gray-400">Overloaded Caregivers</p>
          <p className="mt-1 text-3xl font-bold text-[#EA580C]">{overloadedCount}</p>
          <p className="mt-0.5 text-xs text-gray-400">above 80% workload threshold</p>
        </div>
      </div>

      <div className="grid grid-cols-1 gap-6 xl:grid-cols-3">
        <div className="space-y-4 xl:col-span-2">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <div>
              <h2 className="font-semibold text-[#1F2937]">AI-Generated Suggestions</h2>
              <p className="mt-0.5 text-xs text-gray-400">
                Ranked by projected impact · approve to apply redistribution
              </p>
            </div>

            <div className="flex gap-2">
              {(['all', 'pending', 'approved', 'rejected'] as const).map((f) => (
                <button
                  key={f}
                  type="button"
                  onClick={() => setActiveFilter(f)}
                  className={`rounded-full px-3 py-1 text-xs font-medium transition-colors ${
                    activeFilter === f
                      ? 'bg-[#1E3A8A] text-white'
                      : 'bg-gray-100 text-gray-500 hover:bg-gray-200'
                  }`}
                >
                  {f === 'all' ? 'All' : f.charAt(0).toUpperCase() + f.slice(1)}
                  {f === 'pending' && pendingCount > 0 ? (
                    <span className="ml-1 rounded-full bg-red-500 px-1.5 text-[10px] text-white">
                      {pendingCount}
                    </span>
                  ) : null}
                </button>
              ))}
            </div>
          </div>

          {filteredSuggestions.length === 0 ? (
            <div className="rounded-2xl border border-gray-100 bg-white p-12 text-center">
              <ArrowRightLeft size={32} className="mx-auto mb-3 text-gray-200" aria-hidden />
              <p className="text-sm text-gray-400">No suggestions in this category</p>
            </div>
          ) : (
            <div className="space-y-4">
              {filteredSuggestions.map((suggestion, index) => (
                <div
                  key={suggestion.id}
                  className="animate-fadeInUp"
                  style={{ animationDelay: `${index * 80}ms` }}
                >
                  <RedistributionCard
                    suggestion={suggestion}
                    onApprove={handleApprove}
                    onReject={handleReject}
                    onModify={handleModify}
                    onUndoReject={handleUndoReject}
                  />
                </div>
              ))}
            </div>
          )}
        </div>

        <div className="space-y-6 xl:col-span-1">
          <WorkloadBarChart entries={WORKLOAD_ENTRIES} />
          <ImpactPreviewChart suggestions={suggestions} approvedIds={approvedIds} />
        </div>
      </div>

      <div className="rounded-2xl border border-gray-100 bg-gray-50 p-4">
        <p className="text-xs leading-relaxed text-gray-400">
          <span className="font-medium text-gray-500">Research Note:</span> Redistribution suggestions are
          generated using a rule-based decision engine that compares caregiver risk scores, personal
          baseline deviations, and workload capacity derived from TILES-2018 schedule features. In the
          full system, suggestions would be generated by the trained XGBoost model with SHAP attribution
          indicating which caregiver features make them suitable redistribution candidates. This
          prototype demonstrates the intervention interface as described in Research Objective 6. ·
          Dataset: TILES-2018 © USC Institute for Creative Technologies — used under academic research
          license.
        </p>
      </div>
    </div>
  )
}
