import {
  AlertTriangle,
  Angry,
  Apple,
  Armchair,
  ArrowLeft,
  ArrowRight,
  BatteryLow,
  BedDouble,
  Building2,
  Check,
  Clock,
  Coffee,
  CupSoda,
  DoorOpen,
  Droplet,
  Droplets,
  Egg,
  Footprints,
  Frown,
  Ghost,
  Gift,
  Grab,
  Hand,
  Heart,
  HeartCrack,
  HelpCircle,
  LifeBuoy,
  Loader,
  MessageCircle,
  Milk,
  Octagon,
  PartyPopper,
  PersonStanding,
  Phone,
  Pill,
  RockingChair,
  Sandwich,
  Smile,
  Soup,
  Stethoscope,
  Sun,
  Sunrise,
  Thermometer,
  ThumbsUp,
  TrendingDown,
  Users,
  UserRound,
  Utensils,
  Wind,
  X,
  XCircle,
  type LucideIcon,
} from 'lucide-react'

// Centralised sign -> icon map. Each icon is chosen to visually hint at
// the meaning of that specific word (with sensible reuse for closely
// related words). Presentation only — this file has no logic and no
// bearing on recognition, scoring, or the sign list itself.
export const signIconMap: Record<string, LucideIcon> = {
  afternoon: Sun,
  angry: Angry,
  arm: Hand,
  back: ArrowLeft,
  bread: Sandwich,
  call: Phone,
  close: X,
  coffee: Coffee,
  come: Hand,
  comfortable: Armchair,
  confused: HelpCircle,
  cough: Wind,
  danger: AlertTriangle,
  dizzy: Loader,
  doctor: Stethoscope,
  drink: CupSoda,
  eat: Utensils,
  egg: Egg,
  fruit: Apple,
  give: Gift,
  go: ArrowRight,
  good: ThumbsUp,
  happy: Smile,
  head: UserRound,
  hello: Hand,
  help: LifeBuoy,
  hospital: Building2,
  hot: Thermometer,
  hungry: Soup,
  hurt: HeartCrack,
  me: UserRound,
  meet: Users,
  milk: Milk,
  morning: Sunrise,
  mouth: MessageCircle,
  no: XCircle,
  nose: Wind,
  open: DoorOpen,
  pain: HeartCrack,
  please: Heart,
  sad: Frown,
  scared: Ghost,
  sick: Pill,
  sit: RockingChair,
  sleep: BedDouble,
  sorry: Frown,
  stand: PersonStanding,
  stomach: Soup,
  stop: Octagon,
  take: Grab,
  tea: Coffee,
  thirsty: Droplet,
  tired: BatteryLow,
  wait: Clock,
  walk: Footprints,
  water: Droplets,
  weak: TrendingDown,
  welcome: PartyPopper,
  yes: Check,
}

const FALLBACK_ICON: LucideIcon = Hand

export function getSignIcon(signId: string): LucideIcon {
  return signIconMap[signId.toLowerCase()] ?? FALLBACK_ICON
}
