import { FileDown, Headphones, Mic, RefreshCw, Volume2, Eye, Printer, FileText, Mic2 } from 'lucide-react'
import { useEffect, useMemo, useRef, useState } from 'react'
import { Button } from '../../../shared/components/Button'
import { PatientAvatar } from '../components/PatientAvatar'
import { StatusBadge } from '../components/StatusBadge'
import { AudioSummaryPlayer } from '../components/AudioSummaryPlayer'
import { VoiceAssistantAvatar, type VoiceAssistantHandle } from '../components/VoiceAssistantAvatar'
import type { HandoverSummaryItem, Patient } from '../data/mockCareData'
import { handoverSummaries, patients } from '../data/mockCareData'
import { useVoiceLogUI } from '../components/VoiceLogLayout'

/* ── helpers ─────────────────────────────────────────────── */

function downloadText(filename: string, text: string, mime = 'text/plain') {
  const blob = new Blob([text], { type: mime })
  const url  = URL.createObjectURL(blob)
  const a    = Object.assign(document.createElement('a'), { href: url, download: filename })
  document.body.appendChild(a)
  a.click()
  a.remove()
  // delay revocation so the browser has time to initiate the download
  setTimeout(() => URL.revokeObjectURL(url), 200)
}

function openPrintPreview(summary: HandoverSummaryItem, patient: Patient) {
  const win = window.open('', '_blank', 'width=820,height=700')
  if (!win) { window.alert('Pop-up blocked — please allow pop-ups for this site.'); return }

  win.document.write(`<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Handover Summary — ${summary.patientId}</title>
  <style>
    *  { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: system-ui, -apple-system, sans-serif; color: #0F172A;
           padding: 48px 56px; max-width: 720px; margin: 0 auto; }
    .brand  { font-size: 22px; font-weight: 800; color: #1E3A8A; letter-spacing: -0.5px; }
    .brand span { color: #7C3AED; }
    .tagline { font-size: 12px; color: #64748B; margin-top: 2px; }
    hr  { border: none; border-top: 2px solid #1E3A8A; margin: 20px 0; }
    h2  { font-size: 16px; font-weight: 700; margin-bottom: 14px; color: #1E3A8A; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 28px; font-size: 13px; }
    th  { text-align: left; font-size: 10px; font-weight: 700; text-transform: uppercase;
          letter-spacing: .06em; color: #64748B; background: #F8FAFC;
          padding: 8px 12px; border-bottom: 1px solid #E2E8F0; }
    td  { padding: 9px 12px; border-bottom: 1px solid #F1F5F9; }
    td:first-child { font-weight: 600; color: #475569; width: 160px; }
    .notes { background: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 10px;
             padding: 18px; font-size: 13px; line-height: 1.7; color: #374151; white-space: pre-wrap; }
    .footer { margin-top: 40px; padding-top: 14px; border-top: 1px solid #E2E8F0;
              font-size: 11px; color: #94A3B8; display: flex; justify-content: space-between; }
    .actions { margin-top: 28px; display: flex; gap: 10px; }
    .btn { padding: 10px 22px; border-radius: 8px; font-size: 13px; font-weight: 600;
           cursor: pointer; border: none; }
    .btn-primary { background: #1E3A8A; color: #fff; }
    .btn-secondary { background: #F1F5F9; color: #1E3A8A; border: 1px solid #E2E8F0; }
    @media print {
      .actions { display: none; }
      body { padding: 24px 32px; }
    }
  </style>
</head>
<body>
  <div class="brand">Care<span>Sense</span></div>
  <div class="tagline">Intelligent Care Support — Patient Handover Report</div>
  <hr />
  <h2>Patient Details</h2>
  <table>
    <thead><tr><th>Field</th><th>Value</th></tr></thead>
    <tbody>
      <tr><td>Patient ID</td><td><strong>${summary.patientId}</strong></td></tr>
      <tr><td>Patient Name</td><td>${patient.name}</td></tr>
      <tr><td>Branch</td><td>${summary.branch}</td></tr>
      <tr><td>Room</td><td>${summary.room}</td></tr>
      <tr><td>Shift Date</td><td>${summary.date}</td></tr>
      <tr><td>Last Updated</td><td>${summary.updatedAt}</td></tr>
      <tr><td>Status</td><td>${summary.status}</td></tr>
      <tr><td>Voice Enabled</td><td>${summary.voiceEnabled ? 'Yes' : 'No'}</td></tr>
    </tbody>
  </table>
  <h2>Handover Notes</h2>
  <div class="notes">${summary.summary.replace(/</g, '&lt;')}</div>
  <div class="footer">
    <span>Generated by CareSense</span>
    <span>${new Date().toLocaleString()}</span>
  </div>
  <div class="actions">
    <button class="btn btn-primary" onclick="window.print()">🖨&nbsp; Print / Save as PDF</button>
    <button class="btn btn-secondary" onclick="window.close()">Close</button>
  </div>
</body>
</html>`)
  win.document.close()
}

export function HandoverSummariesPage() {
  const { branch, openRecorder } = useVoiceLogUI()
  const [patientFilter, setPatientFilter] = useState<'All' | string>('All')
  const [dateFilter, setDateFilter] = useState<string>('')

  const baseList = useMemo(
    () => (branch === 'All Branches' ? handoverSummaries : handoverSummaries.filter((s) => s.branch === branch)),
    [branch],
  )

  const availableDates = useMemo(() => {
    const set = new Set<string>()
    for (const s of baseList) set.add(s.date)
    return Array.from(set).sort().reverse()
  }, [baseList])

  useEffect(() => {
    // Default date filter to newest available date (usually today).
    if (!dateFilter && availableDates.length) setDateFilter(availableDates[0]!)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [availableDates.join('|')])

  const list = useMemo(() => {
    let out = baseList
    if (patientFilter !== 'All') out = out.filter((s) => s.patientId === patientFilter)
    if (dateFilter) out = out.filter((s) => s.date === dateFilter)
    return out
  }, [baseList, dateFilter, patientFilter])

  const [selectedId, setSelectedId] = useState<string>(handoverSummaries[0]!.id)
  const selected = list.find((s) => s.id === selectedId) ?? list[0] ?? handoverSummaries[0]!
  const patient = patients.find((p) => p.id === selected.patientId) ?? patients[0]!

  useEffect(() => {
    // Keep selection valid when filters change.
    if (!list.some((x) => x.id === selectedId) && list[0]) setSelectedId(list[0].id)
  }, [list, selectedId])

  const assistantRef = useRef<VoiceAssistantHandle | null>(null)
  const [playing, setPlaying] = useState(false)

  return (
    <div className="grid gap-4">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <div className="text-2xl font-extrabold tracking-tight">Handover Summaries</div>
          <div className="mt-1 text-sm vl-subtle">
            Generate and playback voice-enabled shift handovers with export options.
          </div>
        </div>
        <div className="flex flex-wrap items-center gap-2">
          <Button className="vl-btn" variant="primary" size="sm" onClick={openRecorder}>
            <span className="inline-flex items-center gap-2">
              <Mic size={16} />
              Tap to Speak
            </span>
          </Button>
          <Button className="vl-btn" variant="secondary" size="sm" onClick={() => window.alert('Mock: Generate summaries')}>
            <span className="inline-flex items-center gap-2">
              <Headphones size={16} />
              Generate
            </span>
          </Button>
        </div>
      </div>

      <div className="vl-handoverGrid">
        <div className="vl-card vl-handoverLeft">
          <div className="vl-cardHeader">
            <div>
              <div className="vl-cardTitle">Generated summaries</div>
              <div className="text-xs vl-subtle">Select one to view and play</div>
            </div>
            <span className="vl-chip">{list.length} items</span>
          </div>
          <div className="vl-cardBody">
            <div className="mb-3 flex flex-wrap items-center gap-2">
              <span className="vl-chip">
                <span className="text-[11px] font-bold" style={{ color: 'var(--vl-primary)' }}>
                  Patient
                </span>
                <select
                  className="bg-transparent text-xs font-semibold outline-none"
                  value={patientFilter}
                  onChange={(e) => setPatientFilter(e.target.value)}
                  aria-label="Filter by patient ID"
                >
                  <option value="All">All</option>
                  {patients
                    .map((p) => p.id)
                    .sort()
                    .map((id) => (
                      <option key={id} value={id}>
                        {id}
                      </option>
                    ))}
                </select>
              </span>

              <span className="vl-chip">
                <span className="text-[11px] font-bold" style={{ color: 'var(--vl-primary)' }}>
                  Date
                </span>
                <select
                  className="bg-transparent text-xs font-semibold outline-none"
                  value={dateFilter}
                  onChange={(e) => setDateFilter(e.target.value)}
                  aria-label="Filter by date"
                >
                  {availableDates.map((d) => (
                    <option key={d} value={d}>
                      {d}
                    </option>
                  ))}
                </select>
              </span>
            </div>

            <div className="vl-tableScroll vl-handoverTable" style={{ borderRadius: 14 }}>
              <table className="min-w-[620px] w-full border-separate border-spacing-0">
                <thead>
                  <tr className="text-left text-xs font-extrabold tracking-wide text-[rgba(15,23,42,0.55)]">
                    {['Patient', 'Branch', 'Last updated', 'Status', 'Actions'].map((h) => (
                      <th key={h} className="border-b px-4 py-3" style={{ borderColor: 'rgba(15,23,42,0.08)' }}>
                        {h}
                      </th>
                    ))}
                  </tr>
                </thead>
                <tbody>
                  {list.map((s) => {
                    const p = patients.find((pp) => pp.id === s.patientId)
                    return (
                      <tr
                        key={s.id}
                        className={[
                          'cursor-pointer bg-white transition',
                          selectedId === s.id ? 'bg-[rgba(238,242,255,0.75)]' : 'hover:bg-[rgba(238,242,255,0.55)]',
                        ].join(' ')}
                        onClick={() => setSelectedId(s.id)}
                      >
                        <td className="border-b px-4 py-3" style={{ borderColor: 'rgba(15,23,42,0.06)' }}>
                          <div className="flex items-center gap-3">
                            <PatientAvatar name={p?.name ?? s.patientId} gender={p?.gender ?? 'Female'} size={38} />
                            <div className="leading-tight">
                              <div className="text-sm font-extrabold">{s.patientId}</div>
                              <div className="text-xs vl-subtle">{p?.room ?? s.room}</div>
                            </div>
                          </div>
                        </td>
                        <td className="border-b px-4 py-3" style={{ borderColor: 'rgba(15,23,42,0.06)' }}>
                          <span className="text-sm font-semibold">{s.branch}</span>
                        </td>
                        <td className="border-b px-4 py-3" style={{ borderColor: 'rgba(15,23,42,0.06)' }}>
                          <span className="text-sm font-semibold">{s.updatedAt}</span>
                        </td>
                        <td className="border-b px-4 py-3" style={{ borderColor: 'rgba(15,23,42,0.06)' }}>
                          <StatusBadge
                            label={s.status}
                            tone={s.status === 'Ready' ? 'good' : s.status === 'Processing' ? 'info' : 'warn'}
                            pulse={s.status === 'Needs Review'}
                          />
                        </td>
                        <td className="border-b px-4 py-3" style={{ borderColor: 'rgba(15,23,42,0.06)' }}>
                          <div className="flex items-center gap-2" onClick={(e) => e.stopPropagation()}>
                            <Button className="vl-btn" variant="secondary" size="sm" onClick={() => setSelectedId(s.id)}>
                              <span className="inline-flex items-center gap-2">
                                <Eye size={16} />
                                View
                              </span>
                            </Button>
                          </div>
                        </td>
                      </tr>
                    )
                  })}
                </tbody>
              </table>
            </div>
          </div>
        </div>

        <div className="vl-handoverRight">
          <div className="vl-card vl-handoverCard">
            <div className="vl-cardHeader">
              <div className="flex items-center gap-3">
                <PatientAvatar name={patient.name} gender={patient.gender} size={46} />
                <div>
                  <div className="vl-cardTitle">Selected summary</div>
                  <div className="text-xs vl-subtle">
                    {selected.patientId} • {selected.branch} • Room {selected.room}
                  </div>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <StatusBadge label={selected.voiceEnabled ? 'Voice enabled' : 'Text only'} tone={selected.voiceEnabled ? 'good' : 'neutral'} />
                <Button className="vl-btn" variant="secondary" size="sm" onClick={() => window.alert('Mock: Regenerate summary')}>
                  <span className="inline-flex items-center gap-2">
                    <RefreshCw size={16} />
                    Regenerate
                  </span>
                </Button>
              </div>
            </div>
            <div className="vl-cardBody">
              <VoiceAssistantAvatar
                ref={assistantRef}
                variant="maleAssistant"
                text={selected.summary}
                title="Male Caregiver Assistant"
                subtitle={`Reading ${selected.patientId} • ${selected.date}`}
                onStart={() => setPlaying(true)}
                onStop={() => setPlaying(false)}
              />
              <div className="vl-summaryBox">
                {selected.summary}
              </div>
              <div className="vl-summaryMeta">
                <span className="vl-chip">
                  <Volume2 size={14} />
                  Auto-play ready
                </span>
                <span className="vl-chip">Updated: {selected.updatedAt}</span>
              </div>
            </div>
          </div>

          <AudioSummaryPlayer
            className="vl-handoverCard"
            resetKey={selected.id}
            playing={playing}
            onPlayingChange={setPlaying}
            onPlaySummary={() => {
              // When user hits play on the audio widget, speak via assistant too.
              assistantRef.current?.speak()
            }}
          />

          <div className="vl-card vl-handoverCard">
            <div className="vl-cardHeader">
              <div>
                <div className="vl-cardTitle">Download options</div>
                <div className="text-xs vl-subtle">Export summary in your preferred format</div>
              </div>
              <span className="vl-chip">
                <FileDown size={14} />
                Export
              </span>
            </div>
            <div className="vl-cardBody">
              <div className="vl-downloadRow">
                {/* PDF — opens a formatted print-preview in a new tab */}
                <Button
                  className="vl-btn"
                  variant="primary"
                  size="sm"
                  onClick={() => openPrintPreview(selected, patient)}
                  title="Opens a print-ready report — use Print → Save as PDF"
                >
                  <span className="inline-flex items-center gap-2">
                    <Printer size={16} />
                    Download PDF
                  </span>
                </Button>

                {/* Summary — plain-text file download */}
                <Button
                  className="vl-btn"
                  variant="secondary"
                  size="sm"
                  onClick={() =>
                    downloadText(
                      `handover-${selected.patientId}-${selected.date}.txt`,
                      [
                        `CareSense — Handover Summary`,
                        `Patient : ${selected.patientId}  (${patient.name})`,
                        `Branch  : ${selected.branch}`,
                        `Room    : ${selected.room}`,
                        `Date    : ${selected.date}`,
                        `Updated : ${selected.updatedAt}`,
                        `Status  : ${selected.status}`,
                        '',
                        '── Notes ─────────────────────────────────',
                        selected.summary,
                        '',
                        `Generated by CareSense · ${new Date().toLocaleString()}`,
                      ].join('\n'),
                    )
                  }
                >
                  <span className="inline-flex items-center gap-2">
                    <FileText size={16} />
                    Download Summary
                  </span>
                </Button>

                {/* Audio — uses browser TTS to speak the summary aloud */}
                <Button
                  className="vl-btn"
                  variant="secondary"
                  size="sm"
                  onClick={() => assistantRef.current?.speak()}
                  title="Plays the summary via browser Text-to-Speech"
                  disabled={!selected.voiceEnabled}
                >
                  <span className="inline-flex items-center gap-2">
                    <Mic2 size={16} />
                    Play Audio
                  </span>
                </Button>
              </div>
              <div className="mt-3 text-xs vl-subtle">
                PDF opens a print-ready preview · Summary saves as .txt · Audio plays via TTS
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}

