import { getStoredUser } from '../config/auth'

export type PerformanceReportPayload = {
  caregiverName?: string
  generatedAt?: Date
}

const DEFAULT_NAME = 'CareSense Caregiver'

export function generateCareSenseReportHtml(options?: PerformanceReportPayload): string {
  const user = getStoredUser()
  const name = options?.caregiverName ?? user?.name ?? DEFAULT_NAME
  const date = (options?.generatedAt ?? new Date()).toLocaleString(undefined, {
    dateStyle: 'medium',
    timeStyle: 'short',
  })

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>CareSense Caregiver Performance Report</title>
  <style>
    :root {
      font-family: 'Segoe UI', system-ui, -apple-system, Roboto, sans-serif;
      color: #334155;
    }
    body { margin: 0; background: linear-gradient(180deg, #faf9ff 0%, #ffffff 40%); padding: 32px; }
    .sheet {
      max-width: 760px;
      margin: 0 auto;
      background: #ffffff;
      border-radius: 20px;
      border: 1px solid rgba(167,139,250,0.35);
      box-shadow: 0 20px 48px rgba(109,40,217,0.1);
      padding: 36px 40px;
    }
    h1 {
      margin: 0 0 6px;
      font-size: 1.65rem;
      letter-spacing: -0.03em;
      color: #0f172a;
    }
    .tagline { font-size: 0.92rem; color: #64748b; margin-bottom: 24px; }
    .meta { display: grid; gap: 6px; font-size: 0.92rem; margin-bottom: 24px; padding: 14px 16px; background: linear-gradient(90deg,#f5f3ff,#ecfdf5); border-radius: 12px; border: 1px solid #ede9fe; }
    .kpi { display: grid; grid-template-columns: repeat(2, minmax(0,1fr)); gap: 12px; margin-bottom: 24px; }
    .kpi div { padding: 12px 14px; border-radius: 14px; background: #f8fafc; border: 1px solid #e2e8f0; }
    .kpi strong { font-size: 1.35rem; color: #0f172a; display: block; }
    section { margin-top: 22px; }
    h2 { font-size: 1.05rem; color: #5b21b6; margin: 0 0 12px; }
    table { width: 100%; border-collapse: collapse; font-size: 0.88rem; }
    th, td { text-align: left; padding: 8px 10px; border-bottom: 1px solid #eef2ff; }
    th { background: #f5f3ff; color: #4c1d95; font-weight: 600; }
    ul { margin: 0; padding-left: 1.25rem; line-height: 1.55; }
    .footer { margin-top: 28px; font-size: 0.75rem; color: #94a3b8; text-align: center; }
    @media print { body { padding: 0; } .sheet { box-shadow: none; } }
  </style>
</head>
<body>
  <div class="sheet">
    <h1>CareSense Caregiver Performance Report</h1>
    <p class="tagline">AI-assisted tutoring snapshot — expressive signing &amp; observation training (sample)</p>
    <div class="meta">
      <div><strong>Caregiver:</strong> ${escapeHtml(name)}</div>
      <div><strong>Date:</strong> ${escapeHtml(date)}</div>
    </div>
    <div class="kpi">
      <div><span>Overall score</span><strong>86%</strong></div>
      <div><span>Lessons completed</span><strong>18/20</strong></div>
      <div><span>Average accuracy</span><strong>86%</strong></div>
      <div><span>Current streak</span><strong>4 days</strong></div>
    </div>
    <section>
      <h2>Sign language performance</h2>
      <table>
        <thead><tr><th>Sign</th><th>Accuracy</th></tr></thead>
        <tbody>
          <tr><td>Thank You</td><td>92%</td></tr>
          <tr><td>Help</td><td>88%</td></tr>
          <tr><td>Eat</td><td>76%</td></tr>
          <tr><td>Drink</td><td>90%</td></tr>
        </tbody>
      </table>
    </section>
    <section>
      <h2>Non-verbal vitals training (education-only)</h2>
      <table>
        <thead><tr><th>Lesson</th><th>Status</th></tr></thead>
        <tbody>
          <tr><td>Resting Tremor</td><td>Completed</td></tr>
          <tr><td>Bradykinesia</td><td>In Progress</td></tr>
          <tr><td>Rigidity</td><td>Not started</td></tr>
          <tr><td>Postural Instability</td><td>Not started</td></tr>
          <tr><td>Masked Face</td><td>Completed</td></tr>
        </tbody>
      </table>
    </section>
    <section>
      <h2>Strengths</h2>
      <ul>
        <li>Consistent practice rhythm</li>
        <li>Good hand-shape accuracy</li>
        <li>Improved observation skills</li>
      </ul>
    </section>
    <section>
      <h2>Recommendations</h2>
      <ul>
        <li>Practise movement speed control</li>
        <li>Hold final sign position longer</li>
        <li>Continue non-verbal cue observation lessons</li>
      </ul>
    </section>
    <p class="footer">Generated by CareSense · Educational prototype report · Not a clinical document</p>
  </div>
</body>
</html>`
}

function escapeHtml(s: string) {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

export function downloadCareSensePerformanceReport(payload?: PerformanceReportPayload) {
  const html = generateCareSenseReportHtml(payload)
  const blob = new Blob([html], { type: 'text/html;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  const safe =
    typeof payload?.generatedAt?.getTime === 'function'
      ? payload.generatedAt!.getTime()
      : Date.now()
  a.href = url
  a.download = `CareSense_Report_${safe}.html`
  a.rel = 'noopener'
  document.body.appendChild(a)
  a.click()
  a.remove()
  URL.revokeObjectURL(url)
}
