-- ============================================================
-- 0015_SCRIBE_period_summaries.sql
-- SCRIBE Component — Voice ADL Logging (Component 4)
-- Cached period handover summaries (text + TTS audio on R2).
-- Generated on demand by the backend (Stages 6–7).
--
-- Depends on: public.is_admin() (0002_profiles.sql),
--             public.is_supervisor() (0013_SCRIBE_adl_records.sql)
--
-- Write path: all inserts/updates are backend-only (service_role).
-- Supervisors have SELECT only via the authenticated client.
-- ============================================================

create table period_summaries (
  id              uuid primary key default gen_random_uuid(),
  patient_id      bigint not null references patients(id),
  start_date      date not null,
  end_date        date not null,
  summary_text    text,
  r2_audio_key    text,
  generated_at    timestamptz not null default now(),
  unique (patient_id, start_date, end_date)
);

comment on table period_summaries is
  'SCRIBE: cached period handover summaries per patient.
  summary_text is the generated report; r2_audio_key points to
  cached TTS audio on R2 (e.g. scribe/summaries/P01/2026-01-01_2026-01-07.mp3).
  Regenerated by the backend when a supervisor requests a period summary.';

create index idx_period_summaries_patient_dates
  on period_summaries (patient_id, start_date desc, end_date desc);

alter table period_summaries enable row level security;

create policy "Admins can manage period summaries"
  on period_summaries for all
  using (public.is_admin())
  with check (public.is_admin());

create policy "Supervisors can read period summaries"
  on period_summaries for select
  using (public.is_supervisor());

grant select on period_summaries to authenticated;
grant select, insert, update, delete on period_summaries to service_role;
